### ISSUE TITLE
Problemas con la práctica 2.

### ISSUE THREAD

**Issue by FranciscoNaveros** [jesusgn90/Try-2-Learn#1]
Hola.
En el guión de prácticas se especifica lo siguiente:
En la documentación de este hito, que se integrará como el resto en el README.md del proyecto, se explicará por qué se ha elegido el sistema de test y de integración continua.

Además tienes que cumplir 3 objetivos:
3 puntos: Configuración correcta de herramientas de construcción.
5 puntos: Integración continua funcionando.
2 puntos: Tests significativos y/o avance del proyecto en sí más allá de lo básico.

Quiero que me detalles en el README todos los pasos que has seguido para hacer esta práctica y me los justifiques.

En configuración correcta de herramientas de contrucción se refiere a que hagas un makefile (o cualquier otra opción que te parezca) para realizar todas las tareas con una sola orden. Por ejemplo, para pasar los test en local, que sea simplemente hacer make test y que esto llame a mocha test/test.js, python test.py o lo que sea que uses para pasar los test.

Este makefile irá aumentando con cada práctica.

**Comment by FranciscoNaveros** [comment]
Además, tienes que tener el 80 % de los ejercicios del tema 2 para que se te evalue la práctica. Hasta ese entonces, tendras un 0 en la práctica 2.

**Comment by jesusgn90** [comment]
Ya he creado un Makefile funcional y realizado otro ejercicio para alcanzar el 80% ahora creo que si esta todo
