### ISSUE TITLE
Faltan ejercicios y objetivos

### ISSUE THREAD

**Issue by FranciscoNaveros** [jesusgn90/Try-2-Learn#2]
Te faltan los ejercicios y los objetivos del tema 4. Entregalos lo antes posible o no podremos corregirte el hito 4.

**Comment by jesusgn90** [comment]
Soy consciente,he tenido mucho trabajo en el puente y no he podido hacer los ejercicios aunque si el hito 4, intentaré para mañana a la noche tenerlo todo!

**Comment by FranciscoNaveros** [comment]
Perfecto.

Ánimo, que ya queda menos.

**Comment by jesusgn90** [comment]
Terminados ejercicios del tema 4 y demás https://github.com/JJ/IV-2015-16/pull/875
